"""
VPN 隧道协议常量定义
"""


class PacketType:
    """隧道协议消息类型"""
    DATA = 0x01
    HEARTBEAT = 0x02
    HEARTBEAT_ACK = 0x03
    HANDSHAKE_CLIENT_HELLO = 0x10
    HANDSHAKE_SERVER_HELLO = 0x11
    HANDSHAKE_FINISHED = 0x12


HANDSHAKE_MSG_CLIENT_HELLO = PacketType.HANDSHAKE_CLIENT_HELLO
HANDSHAKE_MSG_SERVER_HELLO = PacketType.HANDSHAKE_SERVER_HELLO
HANDSHAKE_MSG_FINISHED = PacketType.HANDSHAKE_FINISHED
